security.jwt.secret=VGhpc0lzQVBsYWNlSG9sZGVyMzI1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
security.jwt.expiration-seconds=3600
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
management.endpoints.web.exposure.include=health,info
logging.level.org.springframework.security=INFO