server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
logging.level.com.municipal.user=DEBUG
app.admin.default-email=admin@city.gov
app.admin.default-password=Admin@123