server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: classpath:/config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/